# Generated by Django 6.0.6 on 2026-07-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productcategory_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential Construction'), ('COMMERCIAL', 'Commercial Construction'), ('INDUSTRIAL', 'Industrial Construction'), ('CIVIL', 'Civil Infrastructure')], max_length=50)),
                ('description', models.TextField()),
                ('services_delivered', models.TextField(help_text='Services delivered, separated by comma or newlines.')),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
