# Generated by Django 6.0.6 on 2026-07-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_display',
        ),
    ]
