# Generated by Django 6.0.6 on 2026-07-05 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_service_category_link_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='Link this material highlight to a specific product detail page (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_materials', to='core.product'),
        ),
    ]
